psyche: Label devicesettings_app as coredomain
ERROR: All platform apps must be labeled with a coredomain type.
Please fix the following violations by doing one of these.
1) Add 'coredomain' attribute to labels.
2) Move apps and corresponding seapp_contexts entries to vendor or odm partition.
Violations:
  APK name: XiaomiParts.apk
  package name: org.lineageos.settings
  assigned label: devicesettings_app
---

Also remove unused "sysfs_leds" because it causes conflict with coredomain type.

Signed-off-by: mtkpapa <ebanashka10028@gmail.com>